remote_theme: just-the-docs/just-the-docs

# Required for project sites
url: "https://iammodding.github.io"
baseurl: "/Modding-Stuffs"

color_scheme: dark
nav_enabled: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

heading_anchors: true

plugins:
- jekyll-remote-theme

title: "iAmModding Guide's and Stuff"

callouts:
  warning:
    title: Warning!
    color: red
  important:
    title: Important!
    color: red
  caution:
    title: Caution!
    color: yellow
  tip:
    title: Tip!
    color: green
  mod:
    color: blue
  thanks:
    color: blue

exclude:
  - README.md
  - vendor/
